# Generated by Django 3.2.4 on 2023-08-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20230827_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'ordering': ['-id'], 'verbose_name': 'index', 'verbose_name_plural': 'index'},
        ),
        migrations.AddField(
            model_name='index',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
